server:
  port: 9000
spring:
  main:
    allow-bean-definition-overriding: true

eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: false  #是否从eureka获取注册信息
    register-with-eureka: false #是否将最近注册到eureka
    service-url:          #配置暴露给eureka client的服务地址
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

