server:
  port: 9002 #端口
spring:
  cloud:
    loadbalancer:
      retry:
        enabled: true # 开启Spring Cloud的重试功能
  application:
    name: service-order #服务名称
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shop?useUnicode=true&characterEncoding=utf8
    username: root
    password: root
  jpa:
    database: MySQL
    show-sql: true
    open-in-view: true
  main:
    allow-bean-definition-overriding: true
#配置Eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/,http://localhost:8000/eureka/
  instance:
    prefer-ip-address: true #使用ip地址注册


#logging:
#  level:
#    root: debug

#修改ribbon的负载均衡策略   服务名 -  ribbon - NFLoadBalancerRuleClassName : 策略
#service-product:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule   #设置负载均衡策略
#    ConnectTimeout: 250 # Ribbon的连接超时时间
#    ReadTimeout: 1000 # Ribbon的数据读取超时时间
#    OkToRetryOnAllOperations: true # 是否对所有操作都进行重试
#    MaxAutoRetriesNextServer: 1 # 切换实例的重试次数
#    MaxAutoRetries: 1 # 对当前实例的重试次数

# 配置feign 调用服务的日志输出，日志等级需要去搜下
feign:
  client:
    config:
      service-product:  #要调用的服务名
        loggerLevel: FULL
        readTimeout: 5000
        connectTimeout: 5000
        ribbon:
          readTimeout: 5000
          connectTimeout: 5000
          MaxAutoRetries: 3  #同一台实例最大重试次数，不包括首次调用
          MaxAutoRetriesNextServer: 3 #重试负载均衡其他的实例最大重试次数，不包括首次server
  httpclient:
    enabled: false
  okhttp:
    enabled: true
 #开启对 hystrix的支持
  hystrix:
    enabled: true



