server:
  port: 8031

spring:
  application:
    name: microservice-hystrix-turbine
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/
  instance:
    prefer-ip-address: true
turbine:
# 要监控的微服务列表，多个用,分隔
 appConfig: service-order
 clusterNameExpression: "'default'"
#暴露监控断点
management:
  endpoints:
    web:
      exposure:
        include: '*'